### ISSUE TITLE
MapAPI-  not accessible when hosted on azure

### ISSUE THREAD

**Issue by Xlient** [hkaur008/MLH-hackathon-project#12]
**Describe the bug **🐞
 API doesn't returns a 500 error  when performing GET, POST, PUT & DELETE requests.

**To Reproduce**
 Try to GET REQUEST  in postman on this link  
https://mapapi-1.azure-api.net/?InvCode=QK6A-J 

   -->

**Expected behavior**
  
  Needs to return all users belonging to an organization
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hkaur008** [comment]
I think you solved this !
